set nocompatible

" Needed for vundle, will be turned off after vundle inits 
filetype off

"auto install vundle if it does not exist
let vundle_exists=1
let vundle_readme=expand('~/.vim/bundle/Vundle.vim/README.md')
if !filereadable(vundle_readme)
    echo "Installing Vundle..."
    echo ""
    silent !mkdir -p ~/.vim/bundle
    silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/Vundle.vim
    let vundle_exists=0
endif

"set runtime path to inc Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

"this is the call to begin the Vundle Plugin Operation

call vundle#begin()

" let vundle manage vundle
Plugin 'gmarik/Vundle.vim' 

" Utilities
Plugin 'bling/vim-airline' "provide the fancy statusline on vim
Plugin 'kien/ctrlp.vim' " fuzzy find files
Plugin 'scrooloose/nerdtree' " file drawer, open with :NERDTreeToggle
Plugin 'benmills/vimux' "allows vim to interact with tmux
Plugin 'tpope/vim-fugitive' " the ultimate git helper
Plugin 'tpope/vim-git' 
Plugin 'tpope/vim-commentary' " comment/uncomment lines with gcc or gc in visual mode
Plugin 'Valloric/YouCompleteMe' "Code navigator for C, c++ with back and forth jumps
Plugin 'rdnetto/YCM-Generator' "Generates the .ycm_extra_conf.py for a source directory automatically
Plugin 'SirVer/ultisnips' "snippet engine for repetitive operations
Plugin 'honza/vim-snippets' "snippet to be used by ultisnips
Plugin 'scrooloose/syntastic' "syntax lint checker
Plugin 'chazy/cscope_maps' "provides shortcut cscope maps

" colorschemes
"Plugin 'chriskempson/base16-vim'

" JavaScript plugins
Plugin 'pangloss/vim-javascript'
Plugin 'jelera/vim-javascript-syntax'

"Add following plugins
"bufferline - integrates with vim-airline to display buffers
"syntastic - syntax checker/linter (works for js, c)
"jshint - Javascript linter
"jscs - java script code style
"benmills/vimux - Allows vim to interact with tmux
"js-syntax
"vim-javascript
"supertab
"tabular
"presenting
"scratch
"vim-css-color
":PluginUpdatejs-syntax

call vundle#end()

filetype plugin indent on

set nocompatible "not compatible with vi
set autoread "detect when a file is changed

let mapleader = ","


"Tab control
set tabstop=4 "the visible width of tabs
set shiftwidth=4 "number of spaces to use for indent and unindent
"set textwidth=79 "Sets columns and word wrap
set expandtab "replaces tabs with spaces, aka et
"set noexpandtab "opposite of expand tabs

set smarttab "tab respects 'tabstop', 'shiftwidth', and 'softtabstop'
set softtabstop=4 "edit as if the tabs are 4 character wide
set shiftround "round indent to multiple of 'shiftwidth'

" Set cut/copy buffer as the global OS buffer so you can copy/paste
" into other applications
set clipboard=unnamed

"faster redrawing
set ttyfast

"code folding settings
set foldmethod=syntax "fold based on indent
set foldnestmax=10 "deepest fold is 10 levels
set nofoldenable "don't fold by default
set foldlevel=1


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => User Interface
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"Searching
set ignorecase  "case insensitive searching
set smartcase "case-sensitive if expression contains a capital letter
set hlsearch "aka hls, for highlighting what is being searched
set incsearch "set incremental search, like modern browsers
set nolazyredraw "don't redraw while executing macros

set magic "Set magic on, for regex

set showmatch " show matching braces
set mat=2 " how many tenths of a second to blink

" switch syntax highlighting on
syntax on

set encoding=utf-8
let base16colorspace=256  "Access colors present in 256 colorspace
set t_Co=256 "Explicitly tell vim that the terminal supports 256 colors
"set guifont=Liberation\ Mono\ Powerline\ 10
colorscheme elflord

set number

set autoindent " automatically set indent of new line
set smartindent

set laststatus=2 " show the satus line all the time

"Send all the .swp and .bkp file to another temp directory away from source
"set nobackup
set backupdir=~/.vim-tmp,/var/tmp
set directory=~/.vim-tmp,/var/tmp

"Set color scheme - depending on whether it is gvim or vim
"remember this order is important vim first and then gvim
if v:progname =~? "vim"
    "set guifont=Monospace\ 12
    set guifont=Liberation\ Mono\ Powerline\ 10
    "colorscheme darkblue
    set mouse=a "This activates mouse control in text vim screen on xterm
endif

if v:progname =~? "vimdiff"
    set guifont=Monospace\ 12
    "colorscheme darkblue
    set mouse=a "This activates mouse control in text vimdiff screen on xterm
endif

if v:progname =~? "gvim"
    set columns=100
    set lines=60
    colorscheme default
    set guifont=Ubuntu\ Mono\ 11
		"set guifont=Nimbus\ Mono\ L\ 10
		"set guifont=Efont\ Fixed\ 9 
    "colors elflord
    "Sets no of lines
    "Set columns on screen
endif

"Set fileformat to Unix to prevent problems when sending to Linux machines
"set ff=dos - use this option to set windows based line feeds. This generates
"^M issues in linux
"The key sequence to get ^M is <CTRL>+v+m together
"Use this to get rid of files having ^M
"No need in new VIMs(7.1 and above) as they automatically read windows and unix files
"correctly
"set ffs="unix,dos"

" gvim -b : hex edit binary using xxd-format!
augroup Binary
  au!
  au BufReadPre  *.bin let &bin=1
  au BufReadPost *.bin if &bin | %!xxd
  au BufReadPost *.bin set ft=xxd | endif
  au BufWritePre *.bin if &bin | %!xxd -r
  au BufWritePre *.bin endif
  au BufWritePost *.bin if &bin | %!xxd
  au BufWritePost *.bin set nomod | endif
augroup END

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set history=200	" keep 200 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
"Do this only if vim version >= 7.0 
"setlocal spell spelllang=en_us   "enable spell checking


"Set so that the gvim tabs shows only filenames
function! GuiTabLabel()
    " add the tab number
    let label = '['.tabpagenr()

    " modified since the last save?
    let buflist = tabpagebuflist(v:lnum)
    for bufnr in buflist
        if getbufvar(bufnr, '&modified')
                let label .= '*'
                break
        endif
    endfor

    " count number of open windows in the tab
    let wincount = tabpagewinnr(v:lnum, '$')
    if wincount > 1
        let label .= ', '.wincount
    endif
    let label .= '] '

    " add the file name without path information
    let n = bufname(buflist[tabpagewinnr(v:lnum) - 1])
    let label .= fnamemodify(n, ':t')

    return label
endfunction
set guitablabel=%{GuiTabLabel()}

"set tab heading only if in "vim"
"Help is available as follows:
":h setting-tabline
"Following obtained from here: http://vim.1045645.n5.nabble.com/weird-path-string-on-TAB-line-td1160174.html
if exists("+showtabline")
        function MyTabLine()
                let s = ''
                let t = tabpagenr()
                let i = 1
                while i <= tabpagenr('$')
                        let buflist = tabpagebuflist(i)
                        let winnr = tabpagewinnr(i)
                        let s .= '%' . i . 'T'
                        let s .= (i == t ? '%1*' : '%2*')
                        let s .= ' '
                        "let s .= i . ':'
                        "let s .= winnr . '/' . tabpagewinnr(i,'$')
                        let s .= ' %*'
                        let s .= (i == t ? '%#TabLineSel#' : '%#TabLine#')
                        let file = bufname(buflist[winnr - 1])
                        let file = fnamemodify(file, ':p:t')
                        if file == ''
                                let file = '[No Name]'
                        endif
                        let s .= file
                        let i = i + 1
                endwhile
                let s .= '%T%#TabLineFill#%='
                let s .= (tabpagenr('$') > 1 ? '%999XX' : 'X')
                return s
        endfunction
        set stal=2
        set tabline=%!MyTabLine()
        "map <F12> :tabnext<CR>
        "map! <F12> <C-O>:tabnext<CR>
        "map <S-F12> :tabprev<CR>
        "map! <S-F12> <C-O>:tabprev<CR>
endif 

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Mappings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

map <leader>ev :e! ~/.vimrc<cr> "edit vim config file 
map <leader>et :e! ~/.tmux.conf<cr> "edit tmux config file 
map <leader>ey :e! ~/.vim/.ycm_extra_conf.py<cr> "edit YouCompleteMe config file  
map <leader>ep :e! ~/.bash_profile<cr> "edit bash profile

"To close the buffer that you are currently working on
map <leader>wc :wincmd q<cr>

" moving up and down work as you would expect
"nnoremap <silent> j gj
"nnoremap <silent> k gk

" helpers for dealing with other people's code
nmap \t :set ts=4 sts=4 sw=4 noet<cr>
nmap \s :set ts=4 sts=4 sw=4 et<cr>

"list all buffers and move through them
map <C-l> :buffers<CR>
"map <C-9> :bp<CR>
"map <C-0> :bn<CR>

" Don't use Ex mode, use Q for formatting
map Q gq

"Alternate key map (F4) to help do CTRL + A ie, auto increment numbers
"This is useful in SCREEN sessions where CTRL + A already is trapped for
"changing windows
"noremap <f4> <c-a>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Functions
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"map <C-h> :call WinMove('h')<cr>
"map <C-j> :call WinMove('j')<cr>
"map <C-k> :call WinMove('k')<cr>
"map <C-l> :call WinMove('l')<cr>

" Window movement shortcuts
" move to the window in the direction shown, or create a new window
"function! WinMove(key)
"    let t:curwin = winnr()
"    exec "wincmd ".a:key
"    if (t:curwin == winnr())
"        if (match(a:key,'[jk]'))
"            wincmd v
"        else
"            wincmd s
"        endif
"        exec "wincmd ".a:key
"    endif
"endfunction

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugin settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" close NERDTree after a file is opened
let g:NERDTreeQuitOnOpen=0
" show hidden files in NERDTree
let NERDTreeShowHidden=1
"Prevent funny characters for directories
let g:NERDTreeDirArrows=0

" Toggle NERDTree
nmap <silent> <leader>n :NERDTreeToggle<cr>
" expand to the path of the file in the current buffer
nmap <silent> <leader>f :NERDTreeFind<cr>

" map fuzzyfinder (CtrlP) plugin
" nmap <silent> <leader>t :CtrlP<cr>
" r shortcut stands for recent file lookup
nmap <silent> <leader>r :CtrlPMixed<cr>
let g:ctrlp_map='<leader>t'
let g:ctrlp_dotfiles=1
let g:ctrlp_working_path_mode = 'ra'

" CtrlP ignore patterns
let g:ctrlp_custom_ignore = {
            \ 'dir': '\.git$\|node_modules$\|\.hg$\|\.svn$',
            \ 'file': '\.exe$\|\.so$'
            \ }

" search the nearest ancestor that contains .git, .hg, .svn
let g:ctrlp_working_path_mode = 2

"Mechanism to auto apply .vimrc when it is saved
"if has("autocmd")
"    autocmd bufwritepost .vimrc source $MYVIMRC
"endif

"Enable syntax highlighting of doxygen tags
let g:load_doxygen_syntax=1

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => YouCompleteMe
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"Point to the config file to use for YouCompleteMe
let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"
let g:ycm_autoclose_preview_window_after_completion = 1
"let g:ycm_min_num_identifier_candidate_chars = 4
"let g:ycm_extra_conf_globlist = ['~/repos/*']
let g:ycm_filetype_specific_completion_to_disable = {'javascript': 1}

nnoremap <leader>y :YcmForceCompileAndDiagnostics<cr>
"jump smart (js)
nnoremap <leader>js :YcmCompleter GoTo<CR>
"jump declaration (jd)
nnoremap <leader>jd :YcmCompleter GoToDefinition<CR>
"jump instance (ji)
nnoremap <leader>ji :YcmCompleter GoToDeclaration<CR>
"show data type of variable (display type)
nnoremap <leader>dt :YcmCompleter GetType<CR>
"show parent of this class (display parent)
nnoremap <leader>dp :YcmCompleter GetParent<CR>


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => YCM-Generator
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
nnoremap <leader>gc :YcmGenerateConfig<CR>


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Airline
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:airline#extensions#tabline#enabled = 1 "enables buffer tabs when only one tab is open
"let g:airline_theme = 'tomorrow'
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline#extensions#whitespace#checks = [ ]


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Enable spell checking 
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"We want our cross-machine spell file to be used
set spellfile=~/src/dotfiles/vim/spell/en.utf-8.add
" Toggle and untoggle spell checking
noremap <leader>ss :setlocal spell! spelllang=en_us<cr>

" spelling shortcuts using <leader>
" ]s next misspelled word
" [s previous misspelled word
" zg add to dict
" z= get suggestions
noremap <leader>sn ]s
noremap <leader>sp [s
noremap <leader>sa zg
noremap <leader>su z=

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                UltiSnips                                "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" we can't use <tab> as our snippet key since we use that with YouCompleteMe
let g:UltiSnipsExpandTrigger       = "<c-k>"
let g:UltiSnipsListSnippets        = "<c-m-k>"
"let g:UltiSnipsSnippetsDir         = "~/src/dotfiles/vim/ultisnips"
" Alt conflicts with Xmonad
let g:UltiSnipsJumpForwardTrigger  = "<right>"
let g:UltiSnipsJumpBackwardTrigger = "<left>"
let g:snips_author                 = 'Vijayan Nambiar'

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                syntastic                                "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"let g:syntastic_error_symbol = '.'
"let g:syntastic_warning_symbol = '.'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_python_flake8_args = '--select=F,C9 --max-complexity=10'

let g:syntastic_mode_map = {
       \ "mode": "active",
       \ "active_filetypes": [],
       \ "passive_filetypes": ["dart", "html"] }


" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
