@startuml

title
A __test__ to see what can be done with 
**Activity Diagrams (Beta)** with swimlanes in //PlantUML//

end title

'new_way: create swim lanes for flow isolation
|Swimlane1|

start

'new_way: label arrows as follows
-> setup all entities;

'new_way: Create an activity
partition "Init Sutff" {
:Initialization;
}

'multi-line notes. It auto-attaches to previous activity
note left
This note is on
several lines.
end note

'new_way: to show parallel processing
if (multiprocessor?) then (yes)
    fork
        :Treatment 1;
    fork again
        :Treatment 2;
    end fork
else (single_core)
    -[#blue]-> serial_operation;
    :Treatment 1;
    note right
    This note is on several
    //lines// and can
    contain <b>HTML</b>
    ====
    * Calling the method ""foo()"" is prohibited
    # This is how to create a numbered bullet
    end note
    -[#green]-> serial_operation;
    :Treatment 2;
endif

'new_way: switch to another swimlane with different color
|#LightSkyBlue|Swimlane2|
:foo3;
:foo4;
|Swimlane3|
:foo5;
:foo6;
|Swimlane1|
:foo7;
:foo8;

'new_way: dummy header
header
This is a 
long __dummy__ header
end header

'new_way: dummy footer
footer
This is an
unncessary __dummy__ footer
end footer

'new_way: legend
legend
this is the legend
end legend

'Can also use "end" to get a similar effect
stop


@enduml
